services:
  - type: web
    name: espace-kanaga
    runtime: node
    rootDir: backend
    buildCommand: npm install --include=dev && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: espace-kanaga
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: API_URL
        value: https://espace-kanaga.onrender.com
      - key: PORT
        value: 10000

databases:
  - name: espace-kanaga-db
    databaseName: espacekanaga
    user: espacekanaga
