services:
  - type: web
    name: espace-kanaga
    runtime: node
    rootDir: backend
    buildCommand: npm install --include=dev && npx prisma generate && npm run build
    startCommand: sh start.sh
    envVars:
      - key: DATABASE_URL
        value: postgresql://espacekanaga:xwB07NAGWCoKFv4q1YY0mS300xU7wBde@dpg-d774f0f5r7bs73e5odp0-a.virginia-postgres.render.com:5432/kanaga
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: API_URL
        value: https://espace-kanaga.onrender.com/api
      - key: PORT
        value: 10000

databases:
  - name: espacekanaga
    databaseName: kanaga
    user: espacekanaga
